defaults: &defaults
  site_name:
  assets_dir: jenny
  host: http://192.168.10.123:3000
  js_host: http://edrjs.com
  db: localhost:27017/jenny

development:
  <<: *defaults

production:
  <<: *defaults
